source 'https://rubygems.org'

group :test, :development do
  gem 'rack', '~> 3.2'
  gem 'rackup'
  gem 'webrick'
  gem 'capybara', '~> 3.40'
  gem 'rspec', '~> 3.13'
  gem 'selenium-webdriver', '~> 4.8'
  gem 'percy-capybara', '5.0.0'
end
