name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - uses: actions/cache@v4
        with:
          path: "./vendor/bundle"
          key: v1/${{ runner.os }}/ruby-3.3/${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: v1/${{ runner.os }}/ruby-3.3/
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-20/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/node-20/
      - run: make test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
